Enable x64 clang test
Signed-off-by: Seonghyun Kim <sh8281.kim@samsung.com>

diff --git a/.github/workflows/x64_test_clang.yml b/.github/workflows/x64_test_clang.yml
--- a/.github/workflows/x64_test_clang.yml
+++ b/.github/workflows/x64_test_clang.yml
@@ -67,62 +67,66 @@ jobs:
               body: 'Please check the build status.'
             })
 
-  # test_clang:
-  #   needs: build_x64_clang
-  #   timeout-minutes: 60
-  #   runs-on: [ runner-type3 ]
-  #   container:
-  #     image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
-  #     credentials:
-  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
-  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
-  #     options: --user root
+  test_clang:
+    needs: build_x64_clang
+    timeout-minutes: 60
+    runs-on: [ runner-type3 ]
+    container:
+      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
+      credentials:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+      options: --user root
 
-  #   steps:
-  #     - name: Checkout source..
-  #       uses: CODE-Actions/checkout@v2
-  #       with:
-  #         submodules: false
-  #         ref: ${{ github.event.pull_request.head.sha }}
+    steps:
+      - name: Checkout source..
+        uses: CODE-Actions/checkout@v2
+        with:
+          submodules: false
+          ref: ${{ github.event.pull_request.head.sha }}
 
-  #     - name: Add safe directory
-  #       run: git config --global --add safe.directory /__w/starfish/starfish
+      - name: Add safe directory
+        run: git config --global --add safe.directory /__w/starfish/starfish
 
-  #     - name: Checkout Testcase..
-  #       run: |
-  #         git submodule init
-  #         git submodule update test
+      - name: Checkout Testcase..
+        run: |
+          git submodule init
+          git submodule update test
 
-  #     - uses: CODE-Actions/download-artifact@v2
-  #       with:
-  #         name: starfish-x64_clang_debug
+      - uses: CODE-Actions/download-artifact@v2
+        with:
+          name: starfish-x64_clang_debug
 
-  #     - name: Prepare Test
-  #       run: |
-  #         mkdir -p ~/.fonts
-  #         cp /root/workspace/Ahem.ttf ~/.fonts
-  #         chmod a+x $PWD/out/debug/bin/lightweight-web-engine
-  #         ln -s -f $PWD/out/debug/bin/lightweight-web-engine Starfish
-  #         ln -s $PWD/out/debug/lib/libnanomsg.so ./out/debug/lib/libnanomsg.so.5
-  #         ln -s $PWD/out/debug/lib/libcrypto.so ./out/debug/lib/libcrypto.so.1.1
-  #         ln -s $PWD/out/debug/lib/libssl.so ./out/debug/lib/libssl.so.1.1
-  #         ln -s $PWD/out/debug/lib/libcrypto.so ./out/debug/lib/libcrypto.so.3
-  #         ln -s $PWD/out/debug/lib/libssl.so ./out/debug/lib/libssl.so.3
-  #         /root/workspace/set_up_hosts.sh
+      - name: Prepare Test
+        run: |
+          mkdir -p ~/.fonts
+          cp /root/workspace/Ahem.ttf ~/.fonts
+          chmod a+x $PWD/out/debug/bin/lightweight-web-engine
+          ln -s -f $PWD/out/debug/bin/lightweight-web-engine Starfish
+          ln -s $PWD/out/debug/lib/libnanomsg.so ./out/debug/lib/libnanomsg.so.5
+          ln -s $PWD/out/debug/lib/libcrypto.so ./out/debug/lib/libcrypto.so.1.1
+          ln -s $PWD/out/debug/lib/libssl.so ./out/debug/lib/libssl.so.1.1
+          ln -s $PWD/out/debug/lib/libcrypto.so ./out/debug/lib/libcrypto.so.3
+          ln -s $PWD/out/debug/lib/libssl.so ./out/debug/lib/libssl.so.3
+          /root/workspace/set_up_hosts.sh
 
-  #     - name: Build image diff tool
-  #       run: |
-  #         cmake build/test -G Ninja
-  #         ninja install_pixel_test_dep
+      - name: Build image diff tool
+        run: |
+          cmake build/test -G Ninja
+          ninja install_pixel_test_dep
 
-  #     - name: Run unit-test
-  #       run: |
-  #         xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish unit-test || exit 1
+      # allow failure due to x11 server bug
+      - name: Run unit_test
+        uses: CODE-Actions/nick-fields-retry@v3
+        with:
+          timeout_minutes: 5
+          max_attempts: 5
+          command: xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish unit-test || exit 1
 
-  #     - name: Run internal_test
-  #       run: |
-  #         xvfb-run -s '-screen 0 1920x1080x24' -a ./tool/test_runner.py internal_test || exit 1
+      - name: Run internal_test
+        run: |
+          xvfb-run -s '-screen 0 1920x1080x24' -a ./tool/test_runner.py internal_test || exit 1
 
-  #     - name: Run reftest_all
-  #       run: |
-  #         xvfb-run -s '-screen 0 1920x1080x24' -a ./tool/test_runner.py reftest_all || exit 1
+      - name: Run reftest_all
+        run: |
+          xvfb-run -s '-screen 0 1920x1080x24' -a ./tool/test_runner.py reftest_all || exit 1
